# Generated by Django 3.2 on 2024-01-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240115_1425'),
    ]

    operations = [
    migrations.RemoveField(
        model_name='product',
        name='quantities',
    ),
]
