# Generated by Django 3.2 on 2024-02-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240214_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquantity',
            name='bestsellers_img_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
