# Generated by Django 3.2 on 2024-01-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240115_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='price',
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.quantity')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='quantities',
            field=models.ManyToManyField(through='store.ProductQuantity', to='store.Quantity'),
        ),
    ]
