# Generated by Django 3.2 on 2024-01-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240115_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='productquantity',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
