# Generated by Django 3.2 on 2024-02-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240220_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
