# Generated by Django 3.2 on 2024-03-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20240220_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bestsellers_img_url',
        ),
        migrations.AddField(
            model_name='product',
            name='bestsellers_img',
            field=models.ImageField(blank=True, null=True, upload_to='bestsellers/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_url',
            field=models.FileField(upload_to='products/'),
        ),
    ]
