# Generated by Django 3.2 on 2024-01-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20240117_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
