# Generated by Django 3.2 on 2024-03-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20240304_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name_plural': 'Quantities'},
        ),
    ]
