# Generated by Django 3.2 on 2024-04-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20240329_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('personal', 'Personal Care'), ('grocery', 'Grocery'), ('household', 'Household Essentials')], default='grocery', max_length=20),
        ),
    ]
