# Generated by Django 3.2 on 2024-01-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Return Accepted', 'Return Accepted'), ('Return Rejected', 'Return Rejected'), ('Returned', 'Returned'), ('Replacement Required', 'Replacement Required'), ('Replacement Accepted', 'Replacement Accepted'), ('Replacement Rejected', 'Replacement Rejected'), ('Product Replaced', 'Product Replaced'), ('Replacement Complete', 'Replacement Complete')], default='Pending', max_length=20),
        ),
    ]
