# Generated by Django 3.2 on 2024-01-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_delivery_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='permanent_city',
        ),
        migrations.AddField(
            model_name='order',
            name='permanent_landmark',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='permanent_pincode',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='permanent_state',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='permanent_street',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
