# Generated by Django 3.2 on 2024-02-03 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20240203_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='sale_date',
        ),
        migrations.AddField(
            model_name='salesdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
