# Generated by Django 3.2 on 2024-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Media', models.FileField(blank=True, null=True, upload_to='Uploaded_Media/')),
            ],
        ),
    ]
