# Generated by Django 3.2 on 2024-03-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_media',
            old_name='Upload_Media',
            new_name='upload_media',
        ),
    ]
