# Generated by Django 3.2 on 2024-02-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.DeleteModel(
            name='HomePagePopup',
        ),
    ]
