# Generated by Django 3.2 on 2024-03-31 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backupapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoBackupSettings',
        ),
        migrations.DeleteModel(
            name='BackupHistory',
        ),
        migrations.DeleteModel(
            name='BackupSettings',
        ),
    ]
